[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"
  VITE_API_BASE_URL = "https://kozmik-muzik-backend.onrender.com"
  VITE_GROQ_API_KEY = ""

# Development environment
[context.branch-deploy.environment]
  NODE_ENV = "development"
  VITE_API_BASE_URL = "http://localhost:8790"
